export const GET_CHECKS = 'GET_CHECKS'
export const GET_FAVORITES = 'GET_FAVORITES'
export const ASSIGN_PRODUCT_TO_CHECK = 'ASSIGN_PRODUCT_TO_CHECK'
export const REMOVE_PRODUCT_FROM_CHECK = 'REMOVE_PRODUCT_FROM_CHECK'
